name: docs
on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker run -v $(pwd):/docs --entrypoint mkdocs squidfunk/mkdocs-material:7.1.0 gh-deploy --force --strict